import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideNav from "../../../components/SideNav";
import DashboardHeader from "@/components/DashboardHeader";

const inter = Inter({
  subsets: ["latin"], // Specify the subsets you need
  weight: ["400", "700"], // Specify the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-start items-start flex-row">
          <div className="fixed md:w-64 hidden md:block dark:bg-meta-4">
            <SideNav />
          </div>
          <div className="md:ml-64 dark:bg-meta-4">
            <DashboardHeader />
            {children}</div>
        </div>
      </body>
    </html>
  );
}
